### ISSUE TITLE
Question: Use of json_dumps in Pydantic Models

### ISSUE THREAD

**Issue by atulenko** [zhanymkanov/fastapi_production_template#1]
Hi, and thanks for sharing this! It's always interesting to see how others are structuring their FastAPI projects. Looking over this repo I did have one question I hope you don't mind me asking (please close if you'd rather not have questions). 

In your subclass of the pydantic BaseModel you set the `json_dumps` function to use an orjson based implementation. My understanding of pydantic means this function will be used whenever `model_subclass.json()` is called. However, fastAPI won't actually call .json() and instead will just use its `jsonable_encoder ` function when returning pydantic models from an endpoint.

I know one can directly return a Response class to skip the fastAPI validation so potentially you could be doing something like:

```
@router.get("/endpoint", response_model=SomeModel)
def get_model():
    some_model = SomeModel(...)
    return ORJSONResponse(content=json.loads(some_model.json()))
```

But it would be cool if there was a way to set this up without having to explicitly call .json(). So I'd like to understand how you are using this json_dumps function in practice if you don't mind sharing?

**Comment by zhanymkanov** [comment]
Hey,

That's a great question! 

Yes, the ORJSONModel we have as a base class doesn't bring a lot to the table with performance optimization but sets the ground to do it in the future, once we actually face a serialization bottleneck.

The useful thing about setting our own custom BaseModel is that we can have global changes when we need them.

If you are interested in using `orjson` as a way to speed up the fastapi serialization where it really matters, there is an [article](https://khashtamov.com/ru/fastapi-asyncio-multiprocessing/) from @adilkhash where author describes multiprocessing serialization of large lists of pydantic objects. The article is in Russian, but Google translates it well.

p.s. your example looks a bit redundant and can be done shorter
```python3
@router.get("/endpoint", response_model=SomeModel)
def get_model():
    some_model = SomeModel(...)
    return ORJSONResponse(content=some_model.dict())
```
