### ISSUE TITLE
from redis.asyncio import Redis reported error

### ISSUE THREAD

**Issue by jones-so** [zhanymkanov/fastapi_production_template#11]
from redis.asyncio import Redis
ModuleNotFoundError: No module named 'redis.asyncio'; 'redis' is not a package

Hi,Brother, how to solve this error reported by redis.

**Comment by zhanymkanov** [comment]
Probably, you have an old version of aioredis, whereas the package uses `redis` package.

Check out the https://github.com/zhanymkanov/fastapi_production_template/pull/10

**Comment by jones-so** [comment]
您的邮件创视已经收到，请等待我给您的回复，祝您开心！

**Comment by BabakAmini** [comment]
@zhanymkanov, this is due to a local file called `redis.py` that exists at the same path but lacks the asyncio module. Changing its name to something else fixes the problem.

**Comment by jones-so** [comment]
您的邮件创视已经收到，请等待我给您的回复，祝您开心！
