### ISSUE TITLE
on_event is deprecated in favor of lifespan protocol

### ISSUE THREAD

**Issue by ryanwclark1** [zhanymkanov/fastapi_production_template#4]
The on_event(startup and shutdown) has been depreciated 
https://fastapi.tiangolo.com/advanced/events/

Reference on lifespan protocol:
https://asgi.readthedocs.io/en/latest/specs/lifespan.html

I can create a pull request but wanted to open the issue before proposing changes.

**Comment by zhanymkanov** [comment]
Sure, the PR would be welcome!
