### ISSUE TITLE
How to define custom error responses in docs?

### ISSUE THREAD

**Issue by ntoskrn** [zhanymkanov/fastapi_production_template#6]
Currently, custom exceptions do not get a place on documentation. I have tried responses={}, but with no luck. What's the correct thing to do here? Create a custom pydantic model just for it to show on docs?

**Comment by zhanymkanov** [comment]
Why doesn't `responses` work for you? There is no need to create a pydantic model for that, you can just add a dict object for each error status code. The only limitation (AFAIK) is that each status can have at most one desciption. 

```python3
@router.get(
    "/users",
    response_model=list[UserResponse],
    responses={
        404: {"description": "The token was not found"},
    },
    dependencies=[Depends(valid_jwt_user_data)],
)
async def get_users():
  pass
```
