### ISSUE TITLE
Should 'logconfig' in gunicorn_conf.py takes value from environment variable?

### ISSUE THREAD

**Issue by sitawit** [zhanymkanov/fastapi_production_template#8]
According to `start-dev.sh`, it can take `LOG_CONFIG`
https://github.com/zhanymkanov/fastapi_production_template/blob/c61a71531b647a446b2c62eef6cec6d1d9ec3548/scripts/start-dev.sh#L14

But this is static value.
https://github.com/zhanymkanov/fastapi_production_template/blob/c61a71531b647a446b2c62eef6cec6d1d9ec3548/gunicorn/gunicorn_conf.py#L42

We can change to
`logconfig = os.getenv("LOG_CONFIG", "/src/logging_production.ini")`

What do you think? This will make `LOG_CONFIG` in `.env` has meaning for both dev and prod environment.

**Comment by zhanymkanov** [comment]
Neat! That's a good idea. Would be great to see a PR 👍

**Comment by sitawit** [comment]
Ok, I'll do.

**Comment by zhanymkanov** [comment]
Just noticed that you are mentioning `start-dev` vs `gunicorn_conf`. 

start-dev scripts uses uvicorn, while start-prod uses gunicorn and parses configs from `gunicorn_conf.py`, i.e. your suggestion will not work as described.

Anyway, thank you for your note!
